embed_dim: 600
dropout_rate: 0.5
encoder_dims: [200]
decoder_dims: [200]
activation: tanh

anneal_max: 0.2
anneal_total_step: 2000000

learning_rate: 0.001
weight_decay: 1e-5
learner: adam
epochs: 500
batch_size: 500
eval_batch_size: 200
early_stop_patience: 100
