method: prod-c # avg/prod-t/prod-c
discrepancy: l1  # l1/l2
dis_penalty: 1.0
data_mode: skew # reg/skew

co_sampling: False

backbone:

  control:
    model: PMF
    loss_reduction: mean

  treatment:
    model: PMF
    loss_reduction: ~