discrepancy: l1  # l1/l2
dis_penalty: 1.0
data_mode: reg # reg/skew

co_sampling: False

backbone:

  control:
    model: PMF
    loss_reduction: mean
    batch_size: 256

  treatment:
    model: PMF
    loss_reduction: mean
    batch_size: 256