c: 40.0
alpha: 1e-3
beta: 1e-3
negative_count: 1

co_sampling: True

backbone:
  matching: 
    model: BPR
    loss_reduction: mean

user_module: 
  mlp_layers:
  activation_func: sigmoid
  dropout: 0.0
  bias: True
  batch_norm: False
  
item_module:
  mlp_layers:
  activation_func: sigmoid
  dropout: 0.0
  bias: True
  batch_norm: False