epochs: 10
batch_size: 256

lambda_y: 1.0
lambda_theta: 1e-5
lambda_beta: 1e-5
query_std: 0.01
item_std: 0.01
init_mu: 0.01
with_exposure_covariates: False
alpha1: 1.0
alpha2: 1.0

init_std: 0.01

mu_model_batch_size: 10

