experimentName: lr-ml-1m
searchSpaceFile: ../search_space/lr.yaml

trialCommand: python3 run.py -m LR -d ml-1m --mode tune
trialCodeDirectory: ../..
trialGpuNumber: 1

trialConcurrency: 4               # Run 4 trials concurrently.
maxTrialNumber: 1000              # Generate at most 10 trials.
maxExperimentDuration: 100d       # Stop generating trials after 1 hour.

tuner:                          # Configure the tuning algorithm.
  name: TPE
  classArgs:
    optimize_mode: maximize

# assessor:
#   name: Curvefitting
#   classArgs:
#     epoch_num: 200
#     start_step: 20
#     threshold: 0.9
#     gap: 1

# assessor:
#   name: Medianstop
#   classArgs:
#     optimize_mode: maximize
#     start_step: 200

trainingService:
  platform: local
  useActiveGpu: true
  gpuIndices: 0, 1, 2, 3, 4
  maxTrialNumberPerGpu: 4

experimentWorkingDirectory: ../